language: node_js
install:
    - npm install
notifications:
    slack:
        secure: NCs2BllxnNHp89lpOW65MuGn3gkArY1UIEoB189VzTm9gMs3q0xtg3wtOFWn+x8pbWkNEehULIfQ2Q/LH69Hz94Cl4PySPEBYQsF8CiYGQfaJPQF8PQkpRDuUtOmmSPvtDPkOXc3st1J5a8bo3ATlKw+84D8na2sh50qi74TcVNUFuZihIJ1rvEHQhQrKwOcpe6YjvDvB27xqwXSjW1RzSUMnBU19tUIi7SHEJiaTYKQkH4FZUPc0IREbcT8MbyPoXOPchDpTdPXgGVNsZIF+JMXzc4w6pY2k/jcrzydKlKO3Zsn82Cb6LzYwh07Cra2wQe7lZxkVKyDXSBe4cxFubp+7QgCPlM+95fJxvd3g1oiSd+NXMBpYZoqteFSqiFgbJ4FI0w94jVBd4eMV0vbZjPRLVaWWyKC1G86oV4U2jgxYrosMU2P7q4d5hltMPlUHBFGaHZr5MenrxCjvKOo7ZIbQ/HZ0grgaQkqiDLxBDIc3jdUczLFXkh8TkSQ4omqTfJ47QQ1PjoC6zezYzSk516KARcaVmA3DHp7SbCGCEHMMNFNoMrMIicRJEo+QaQ4Qm8cY6dAwJTD9ea8b25/lQJ88eQBUJyHiyryynHlo7OiGWtFnrO5zTMv72g+35EnTzHuKi3J9mjTO5HbZIVuYqkHHz8sd0fgWyKHMHZWbHk=
