name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - name: Create .env.local
      run: echo FOURSQUARE_ACCESS_TOKEN=${{ secrets.FOURSQUARE_ACCESS_TOKEN }} >> .env.local
    - run: npm run build
