name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
      env:
        FOURSQUARE_ACCESS_TOKEN: '${{ secrets.FOURSQUARE_ACCESS_TOKEN }}'
        SEGA_ID: '${{ secrets.SEGA_ID }}'
        SEGA_PASSWORD: '${{ secrets.SEGA_PASSWORD }}'
        NEXT_TELEMETRY_DISABLED: 1
