name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    concurrency: build_and_deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - uses: google-github-actions/auth@v2
        if: github.actor != 'dependabot[bot]'
        with:
          credentials_json: '${{secrets.FIREBASE_SERVICE_ACCOUNT_HIDEO54}}'
      - run: npm run build
        env:
          FOURSQUARE_ACCESS_TOKEN: '${{ secrets.FOURSQUARE_ACCESS_TOKEN }}'
          SEGA_ID: '${{ secrets.SEGA_ID }}'
          SEGA_PASSWORD: '${{ secrets.SEGA_PASSWORD }}'
          DAM_ID: '${{ secrets.DAM_ID }}'
          DAM_PASSWORD: '${{ secrets.DAM_PASSWORD }}'
          NEXT_TELEMETRY_DISABLED: 1
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIDEO54 }}'
          channelId: live
          projectId: hideo54
